  
shinyUI(pageWithSidebar(
  headerPanel('Prospective Customer'),
  sidebarPanel(
    #textInput("infile", "File Loading:", "E:/kmean.csv") ,
    
    fileInput('file1', 'Choose CSV File',
                accept=c('text/csv',  'text/comma-separated-values,text/plain', '.csv')),
      
      tags$hr(), 
    checkboxInput('header', 'Header', TRUE),
      
    radioButtons('sep', 'Separator',
                   c(Comma=',',
                     Semicolon=';',
                     Tab='\t'),
                   ','),
    #numericInput('Records', 'Record count', 20,  min = 1, max = 100)  ,
    
    #radioButtons("choice", "Predict type:",
    #               c("Prospective Custumer" = "RR_FLAG",
    #                 "Custumer Churning" = "CANCEL_FLAG") ) 	,
    tags$hr(),    
    
    selectInput("models", "Choose a classifying model:",  
	   choices = c("DT", "Baysian","SVM","Randomforest"),"DT"),
    tags$hr(),                      
    checkboxGroupInput("variables", "Variable Lists:",
	#c("KHLX","KHXB","CSRQ","XLBH","KHRQ","KHJB","KZ_KYZJ","KZ_ZQSZ","KZ_JJSZ","KZ_ZZC","KZ_YMZZC","KZ_FPS_KHSZ","KZ_TZZLX","KZ_YXZX","KZ_BNJYL","KZ_BNYJ","KZ_SYJYL","KZ_SYYJ","KZ_ZJJYSJ","KZ_01","KZ_PJZC_KHQ","KZ_YKJE_KHQ","KZ_ZJFL","KZ_ZZL","KZ_KHLY","KZ_KHJZ","KZ_KHHYD","KZ_KHNX","KZ_YJFL","KZ_ZCFL","KZ_YKFL","KZ_TZPHFL","KZ_KHFJ","KZ_KHNXFL","KZ_FXCSNL","KZ_PJZC_2","KZ_ZRZJ_2","KZ_ZCZJ_2","KZ_PJZC_6","KZ_YKJE_6","KZ_PJZC_BN","KZ_PJZC_SN","KZ_MRZQZE_6","KZ_MRQZZE_6","KZ_MRJJZE_6","KZ_YJ_6","KZ_JYL_6","KZ_MRZE_6","KZ_MRGPZE_6","KZ_YKL_6","KZ_SNYJ","KZ_ZRZJ_3","KZ_ZCZJ_3","KZ_ZRGP_3","KZ_ZCGP_3","KZ_QCZC_3","KZ_QMZC_3","KZ_YKL_3","KZ_BYJYL","KZ_BYYJ","KZ_FWFJ","KZ_KHSJLY","KZ_GTKHID","KZ_02","KZ_SJYJL_AG","KZ_PJZC_4","KZ_PJZC_1","KZ_YJ_12","KZ_JYYYKJE","KZ_BYYK","KZ_SYYK","KZ_BYYJ_A","KZ_SYYJ_A","KZ_BNYJ_A","KZ_BYJYL_A","KZ_SYJYL_A","KZ_BNJYL_A","KZ_SNJYL","KZ_DQBH","KZ_KHDJB","KZ_BZYJ","KZ_XEXMH","KZ_SFXXLS","KZ_SFYXLS","KZ_SFZCH","KZ_FWYJ","KZ_FWYJL","KZ_SFYXH","KZ_SFQY","KZ_ZZC_RMB","TRZKZJ","ZC3","JYJE3","YK6" ),
	c("Customer Type"="KHLX",
	"Gender"="KHXB",
	"Age"="CSRQ",
	"Education"="XLBH",
	"Account Date"="KHRQ",
	"Grade"="KHJB",
	"Payment"="KZ_KYZJ",
	"Stock"="KZ_ZQSZ",
	"Fund"="KZ_JJSZ",
	"Asset"="KZ_ZZC",
	"Last Asset"="KZ_YMZZC",
	"Yesterday Trade"="KZ_FPS_KHSZ",
	"Invest Type"="KZ_TZZLX",
	"Market NO"="KZ_YXZX",
	"Trade #"="KZ_BNJYL",
	"Commision (Y)#"="KZ_BNYJ",
	"Trade(M)#"="KZ_SYJYL",
	"Commision(M)#"="KZ_SYYJ",
	"Trade Date"="KZ_ZJJYSJ",
	"Invest Type(1 20% Vs 2 80%)"="KZ_01",
	"Avr(3M) Asset"="KZ_PJZC_KHQ",
	"P&L(3M) $"="KZ_YKJE_KHQ",
	"Capital Type"="KZ_ZJFL",
	"Turnover (6M)"="KZ_ZZL",
	"From"="KZ_KHLY",
	"Net Value"="KZ_KHJZ",
	"Activity"="KZ_KHHYD",
	"Years"="KZ_KHNX",
	"Commision Type"="KZ_YJFL",
	"Asset Type"="KZ_ZCFL",
	"P&L Type"="KZ_YKFL",
	"Invest Interest"="KZ_TZPHFL",
	"Age Grade"="KZ_KHFJ",
	"Open Grade"="KZ_KHNXFL",
	"Risk Cap"="KZ_FXCSNL",
	"Avr Asset(2M)"="KZ_PJZC_2",
	"Import(2M)"="KZ_ZRZJ_2",
	"Export(2M)"="KZ_ZCZJ_2",
	"Avr Asset(6M)"="KZ_PJZC_6",
	"P&L(6M)"="KZ_YKJE_6",
	"Avr Asset(Y)"="KZ_PJZC_BN",
	"Last Asset(Y)"="KZ_PJZC_SN",
	"Bond Invest(6M)"="KZ_MRZQZE_6",
	"Warrant Invest(6M)"="KZ_MRQZZE_6",
	"Fund Invest(6M)"="KZ_MRJJZE_6",
	"Commission Invest(6M)"="KZ_YJ_6",
	"Trade(6M)"="KZ_JYL_6",
	"Deal(6M)"="KZ_MRZE_6",
	"Stock(6M)"="KZ_MRGPZE_6",
	"P&L(6M) In"="KZ_YKL_6",
	"Last Commission(Y)"="KZ_SNYJ",
	"Asset In(3M)$"="KZ_ZRZJ_3",
	"Asset Out(3M)"="KZ_ZCZJ_3","Stock In(3M)"="KZ_ZRGP_3","Stock Out(3M)"="KZ_ZCGP_3","Asset Start(3M)"="KZ_QCZC_3","Asset End(3M)"="KZ_QMZC_3","P&L(3M)"="KZ_YKL_3",
	"Trade(M)"="KZ_BYJYL","Commission(M)"="KZ_BYYJ","Service Type"="KZ_FWFJ","KZ_KHSJLY","KZ_GTKHID",
	"Trade Freq(20% Vs 80%)"="KZ_02",
	"Commission Ratio"="KZ_SJYJL_AG",
	"Avr Asset(4M)"="KZ_PJZC_4","Avr Asset(1M)"="KZ_PJZC_1",
	"Commission(12M)"="KZ_YJ_12",
	"P&L(1M)"="KZ_JYYYKJE",
	"P&L in 1 Month"="KZ_BYYK",
	"P&L in Last Month"="KZ_SYYK",
	"Commissionin Month"="KZ_BYYJ_A",
	"Commission in Last Month"="KZ_SYYJ_A",
	"Commission Year"="KZ_BNYJ_A",
	"Trade Year"="KZ_BYJYL_A","Trade in (M)"="KZ_SYJYL_A","Trade in (Y)"="KZ_BNJYL_A",
	"Trade Last(1Y)"="KZ_SNJYL",
	"Area"="KZ_DQBH",
	"VIP"="KZ_KHDJB",
	"Commission standard"="KZ_BZYJ",
	"Account Type"="KZ_XEXMH",
	"Churn"="KZ_SFXXLS","To churn"="KZ_SFYXLS",
	"Asset>50K"="KZ_SFZCH",
	"Commission$"="KZ_FWYJ",
	"Lasr Commission Ratio"="KZ_FWYJL",
	"Validate"="KZ_SFYXH",
	"Signiture"="KZ_SFQY",
	"RMB"="KZ_ZZC_RMB",
	"Turn Off"="TRZKZJ",
	"Asset Last 3M"="ZC3",
	"Trade Last 3M" ="JYJE3",
	"P&L (6M)"="YK6" ),
	c("KZ_SFQY","TRZKZJ","KZ_FXCSNL","KZ_ZCFL","XLBH", "JYJE3","ZC3", "KHXB","KHJB","KZ_ZZL"))    
	                 
    #dat <- ds[,c("CANCEL_FLAG","KZ_02","KZ_01","KZ_KHJZ","ZC3","KZ_XEXMH","KZ_ZJFL","KZ_SFYXH","KZ_ZCFL", "YK6","KZ_SFZCH","KZ_ZJJYSJ","KZ_BZYJ")]
    
	                                     
                  
    #selectInput('xcol', 'X Variable', c("VALUE","VOLICITY","YEARS")) ,
    #selectInput('ycol', 'Y Variable', c("VALUE","VOLICITY","YEARS"), "YEARS"),
    #sliderInput('percentage', 'Training Dataset(%):',   min = 0, max = 1, value = 0.8, step= 0.1)
  ),
  mainPanel(
  
      h4("Importance of Variables"),
      plotOutput("plot"),
      
      h4("Accurancy"),
      tableOutput("accurancy") 
      #h4("Matrix"),
      #tableOutput("view") 
       
  )
))
